/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Leveldb {
  /**
  * Open a database
  * @param path The path to the database
  */
  static open(path: string): Leveldb
  /**
  * Close the database
  */
  close(): void
  /**
  * Get a value from the database
  * @param key The key to get the value for
  * @returns The value for the key
  */
  get(key: Buffer): Buffer
  /**
  * Put a value into the database
  * @param key The key to put the value under
  * @param value The value to put into the database
  */
  put(key: Buffer, value: Buffer): void
  /**
  * Delete a key from the database
  * @param key The key to delete
  */
  delete(key: Buffer): void
}
